Repository chingu-voyages/Handbook, pull requests merged in 2023-09, with the labels that each got.

#22 Add specific Solo Project requirements by Tier
  README.md
  docs/guides/soloproject/soloproject.md
Labels: documentation

#24 chore(README.md): fix typos and formatting in the document
  README.md
Labels: bug, documentation

#25 Fix Contributors Guide: Overview paragraph
  docs/guides/contributors/contributors.md
Labels: documentation

#26 Update Contributors Guide and Backlog+Wireframe Voyage advice
  docs/guides/contributors/contributors.md
  docs/guides/voyage/voyage.md
Labels: documentation

#27 Update solo project submission link
  docs/gettingstarted/whattodofirst.md
Labels: bug

#34 Feature: Update voyage timeline
  docs/.DS_Store
  docs/guides/.DS_Store
  docs/guides/voyage/.DS_Store
  docs/guides/voyage/assets/How_to_use_when2meet.gif
  docs/guides/voyage/voyage.md
Labels: documentation

#35 Update When2Meet link
  docs/guides/voyage/voyage.md
Labels: bug
