Repository chingu-voyages/Handbook, pull requests merged in 2023-10, with the labels that each got.

#36 Feature/add voyage tips
  docs/guides/voyage/voyage.md
Labels: documentation

#37 Fix/update template links
  docs/guides/voyage/voyage.md
Labels: bug

#38 Change links to Google Drive templates to point to Voyage repo template
  docs/guides/voyage/voyage.md
Labels: bug

#41 Feature/add channel restrictions & deployment advice
  docs/guides/voyage/voyage.md
  docs/resources/techresources/techstack.md
Labels: documentation

#42 Feature/add emoji and Voyage tips
  README.md
  docs/guides/soloproject/soloproject.md
  docs/guides/voyage/voyage.md
Labels: documentation

#44 Merge approved changes
  docs/guides/voyage/voyage.md
Labels: documentation

#45 Add artwork to major Handbook sections
  README.md
  docs/guides/contentcreator/assets/Developer_writing_article.jpeg
  docs/guides/contentcreator/contentcreator.md
  docs/guides/contributors/assets/Developer_contributing_to_OSS.jpeg
  docs/guides/contributors/contributors.md
  docs/guides/pairprog/assets/PairProgramming_coders.jpeg
  docs/guides/pairprog/pairprog.md
  docs/guides/soloproject/assets/SoloProject_coder.jpeg
  docs/guides/soloproject/soloproject.md
  docs/guides/voyage/assets/Team_creating_agile_backlog_board.jpeg
  docs/guides/voyage/voyage.md
  docs/resources/glossary/assets/WebDeveloper_using_glossary.jpeg
  docs/resources/glossary/glossary.md
  docs/resources/projresources/assets/Team_conflict.jpeg
  docs/resources/projresources/teamconflict.md
  docs/resources/techresources/assets/Team_choosing_software_license.jpeg
  docs/resources/techresources/assets/Team_git_workflow.jpeg
  docs/resources/techresources/gitgithub.md
  docs/resources/techresources/softwarelicenses.md
Labels: enhancement

#46 Add artwork to the major sections of the Handbook
  README.md
  docs/guides/contentcreator/assets/Developer_writing_article.jpeg
  docs/guides/contentcreator/contentcreator.md
  docs/guides/contributors/assets/Developer_contributing_to_OSS.jpeg
  docs/guides/contributors/contributors.md
  docs/guides/pairprog/assets/PairProgramming_coders.jpeg
  docs/guides/pairprog/pairprog.md
  docs/guides/soloproject/assets/SoloProject_coder.jpeg
  docs/guides/soloproject/soloproject.md
  docs/guides/voyage/assets/Team_creating_agile_backlog_board.jpeg
  docs/guides/voyage/voyage.md
  docs/resources/glossary/assets/WebDeveloper_using_glossary.jpeg
  docs/resources/glossary/glossary.md
  docs/resources/projresources/agile101.md
  docs/resources/projresources/assets/Effective_team.jpeg
  docs/resources/projresources/assets/Team_conflict.jpeg
  docs/resources/projresources/assets/Two_teammates_helping_each_other.jpeg
  docs/resources/projresources/effectiveteams.md
  docs/resources/projresources/greatteammate.md
  docs/resources/projresources/teamconflict.md
  docs/resources/techresources/assets/Team_choosing_software_license.jpeg
  docs/resources/techresources/assets/Team_git_workflow.jpeg
  docs/resources/techresources/gitgithub.md
  docs/resources/techresources/softwarelicenses.md
Labels: enhancement

#48 Feature/add git resources & new section artwork
  docs/.DS_Store
  docs/gettingstarted/.DS_Store
  docs/gettingstarted/assets/WebDev_getting_started.jpeg
  docs/gettingstarted/assets/WebDevs_helping_each_other.jpeg
  docs/gettingstarted/gettinghelp.md
  docs/gettingstarted/whattodofirst.md
  docs/guides/voyage/voyage.md
  docs/resources/techresources/.DS_Store
  docs/resources/techresources/assets/.DS_Store
  docs/resources/techresources/assets/Team_choosing_techstack.jpeg
  docs/resources/techresources/gitgithub.md
  docs/resources/techresources/techstack.md
Labels: enhancement

#49 Feature/add git resources
  docs/gettingstarted/gettinghelp.md
  docs/gettingstarted/whattodofirst.md
Labels: bug

#50 Add new section images and GitHub/git resources
  docs/.DS_Store
  docs/gettingstarted/.DS_Store
  docs/gettingstarted/assets/WebDev_getting_started.jpeg
  docs/gettingstarted/assets/WebDevs_helping_each_other.jpeg
  docs/gettingstarted/gettinghelp.md
  docs/gettingstarted/whattodofirst.md
  docs/guides/voyage/voyage.md
  docs/resources/techresources/.DS_Store
  docs/resources/techresources/assets/.DS_Store
  docs/resources/techresources/assets/Team_choosing_techstack.jpeg
  docs/resources/techresources/gitgithub.md
  docs/resources/techresources/techstack.md
Labels: enhancement

#51 Feature/add getting started diagram
  README.md
  docs/guides/soloproject/soloproject.md
Labels: enhancement

#52 Add getting started diagram
  README.md
  docs/guides/soloproject/soloproject.md
Labels: documentation

#54 Fix Issue #53 - Add soloproject folder to soloproject link path
  docs/gettingstarted/programs.md
Labels: bug

#55 Fix Solo Project link
  docs/gettingstarted/programs.md
Labels: bug
